sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ramil/docker-react -f Dockerfile.dev .

script:
  - docker run ramil/docker-react npm run test -- --coverage